### ISSUE TITLE
Allow to run a simulation against a hub provisioned by the user

### ISSUE THREAD

**Issue by dluc** [Azure/device-simulation-dotnet#109]
# Type of issue 

- [ ] Bug
- [x] New feature
- [ ] Enhancement

# Description 

When the simulation is created, the client can provide a connection string for a custom IoT Hub, to be used to run the simulation. The connection string is safely stored to support service restarts. When a new connection string is provided, if for some reason the previous simulation was not properly stopped, devices will not be pruned.

**Comment by timlaverty** [comment]
When implementing this we should investigate whether it is possible to query the current subscription for existing IoTHubs; e.g. something like this: https://github.com/Azure-Samples/resource-manager-dotnet-resources-and-groups, ```resourceClient.ResourceGroups.ListResources(resourceGroupName);```.  Doing this would potentially allow us a way to not store credentials (better for security), instead we could store the hub name we last pointed to and look that hub name creds up at web app startup.

**Comment by jillcary** [comment]
Created a new issue for investigation into encrypting and storing using the StorageAdapter https://github.com/Azure/device-simulation-dotnet/issues/129

**Comment by jillcary** [comment]
In response to @timlaverty's comment above, the service does not presently take a user's azure auth information, nor do any of our services other than the UI. In the future using APIs may be a good way to get us out of the business of securely storing user's connection strings.

**Comment by dluc** [comment]
Done. Created https://github.com/Azure/device-simulation-dotnet/issues/142 to track @timlaverty's req
