### ISSUE TITLE
Complete /status endpoint + use one process only

### ISSUE THREAD

**Issue by dluc** [Azure/device-simulation-dotnet#116]
# Type of issue 

- [ ] Bug
- [ ] New feature
- [x] Enhancement

# Description 
Refactor the application to run web service and agent in the same process, so that one cannot crash without the other crashing too.

Complete the status endpoint and add tests
* check IoT Hub
* check storage
* report simulation status from the process

**Comment by timlaverty** [comment]
We can either combine them into the same process or have the web service keep a pointer to the service and use it for ensuring it's healthy.  We should propagate the same design to the telemetry-agent as well.

**Comment by dluc** [comment]
Done in https://github.com/Azure/device-simulation-dotnet/pull/137
