### ISSUE TITLE
Simulation cannot connected all simulated devices

### ISSUE THREAD

**Issue by maple10001** [Azure/device-simulation-dotnet#157]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

Simulation cannot connected all simulated devices.

Total devices| Connected devices
--- | --- 
34k |16.88k
20k | 11.08k | 3
10k | 4.75k

# Steps to reproduce 
1. Deploy a device simulation service with S3 hub, standard_D3_v4 VM  
2. Running a simulation with more than 1k devices

# Expected behavior 
Connected all simulated devices.

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

# Code to reproduce the bug 
```
using Xunit;

public class MyTest
{
    [Fact]
    public void TestToReproduceIssue()
    {
        // Arrange
        ...

        // Act
        ...

        // Assert
        ...
    }
}
```

**Comment by maple10001** [comment]
Device connection issue (nullReference error for device) may caused by [Device registering task skipped by cancellation](https://github.com/Azure/device-simulation-dotnet/blob/72a05e852ab9ba88faf7e903e55936534ff7cc05/Services/Devices.cs#L184).

**Comment by dluc** [comment]
Fixed with OS settings, see https://github.com/Azure/pcs-cli/blob/dluc-simple/solutions/devicesimulation/single-vm/setup.sh
