### ISSUE TITLE
Cannot create all the number of devices in Iot Hub

### ISSUE THREAD

**Issue by maple10001** [Azure/device-simulation-dotnet#158]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
Cannot create all the devices in hub.
...

# Steps to reproduce 

1. Deploy a device simulation service.
2. Run simulation with over 20k devices.

# Expected behavior 
Create all the devices.

# Current behavior 
Restart the simulation to get all the devices.

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

# Code to reproduce the bug 
```
using Xunit;

public class MyTest
{
    [Fact]
    public void TestToReproduceIssue()
    {
        // Arrange
        ...

        // Act
        ...

        // Assert
        ...
    }
}
```

**Comment by dluc** [comment]
Need more info, is this happening all the times? Do the logs contain any exceptions?
