### ISSUE TITLE
Add an easy way to test a simulated device javascript file

### ISSUE THREAD

**Issue by jillcary** [Azure/device-simulation-dotnet#165]
# Type of issue 

- [ ] Bug
- [ ] New feature
- [x] Enhancement

# Description 
When adding a new device with a complicated simulation, it would be great to be able to test the javascript file before running an entire simulation to verify if the correct messages are being sent.

**Comment by troyhopwood** [comment]
This is a feature we are tracking in our backlog. Until then, you can use the OSS Device Model Tester found here: https://github.com/troyhopwood/IoT-Device-Simulation-Model-Tester. Note: This project is not associated with Device Simulation itself.

**Comment by troyhopwood** [comment]
This is a feature we are tracking in our backlog. Until then, you can use the OSS Device Model Tester found here: https://github.com/troyhopwood/IoT-Device-Simulation-Model-Tester. Note: This project is not associated with Device Simulation itself.
