### ISSUE TITLE
Unable to provision new simulated devices with new device models

### ISSUE THREAD

**Issue by JohnGolding** [Azure/device-simulation-dotnet#222]
# Type of issue 

- [X] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

I have succesfully added the lightbulb into the IOT hub preconfigured solution, as per tutorial https://docs.microsoft.com/en-us/azure/iot-accelerators/iot-accelerators-remote-monitoring-test.
However, I am unable to add any further simulated devices with new device models that I have provisioned in the device-simulatiion-dotnet microservice. There new devices appears in IOT hub and the webui but no tags, methods or properties are transferred and telemetry data is not transmitted.

# Steps to reproduce 

1. Follow the above mentioned tutorial (shut down the simulation microservice on vm, start the storage adapter locally, add new device in .json and .js, launch locally and view in your IOT hub
2. Log file shows that the new device is not transmmitting telemetry data, new device appears in hub but without any metadata
Docker Log file for simulation container as follows. New devices are airglide-01 and airglide-02:

:/app$ docker logs e14ebc6b5211
[WARN][2018-06-27 18:04:22.220][WebService.1511924f-fb25-40c8-8ddc-62c84c93fdd1][ConfigData:ProcessOptionalPlaceholders] Environment variables not found, {"varsNotFound":", PCS_LOG_LEVEL"}
[WARN][2018-06-27 18:04:22.421][WebService.1511924f-fb25-40c8-8ddc-62c84c93fdd1][ConfigData:ProcessOptionalPlaceholders] Environment variables not found, {"varsNotFound":", PCS_TWIN_READ_WRITE_ENABLED"}
[WARN][2018-06-27 18:04:22.436][WebService.1511924f-fb25-40c8-8ddc-62c84c93fdd1][ConfigData:ProcessOptionalPlaceholders] Environment variables not found, {"varsNotFound":", PCS_SUBSCRIPTION_DOMAIN"}
[WARN][2018-06-27 18:04:22.454][WebService.1511924f-fb25-40c8-8ddc-62c84c93fdd1][ConfigData:ProcessOptionalPlaceholders] Environment variables not found, {"varsNotFound":", PCS_SUBSCRIPTION_ID"}
[WARN][2018-06-27 18:04:22.454][WebService.1511924f-fb25-40c8-8ddc-62c84c93fdd1][ConfigData:ProcessOptionalPlaceholders] Environment variables not found, {"varsNotFound":", PCS_RESOURCE_GROUP"}
[WARN][2018-06-27 18:04:22.454][WebService.1511924f-fb25-40c8-8ddc-62c84c93fdd1][ConfigData:ProcessOptionalPlaceholders] Environment variables not found, {"varsNotFound":", PCS_IOHUB_NAME"}
[WARN][2018-06-27 18:04:24.403][WebService.1511924f-fb25-40c8-8ddc-62c84c93fdd1][ConfigData:ProcessOptionalPlaceholders] Environment variables not found, {"varsNotFound":", PCS_LOG_LEVEL"}
[WARN][2018-06-27 18:04:24.404][WebService.1511924f-fb25-40c8-8ddc-62c84c93fdd1][ConfigData:ProcessOptionalPlaceholders] Environment variables not found, {"varsNotFound":", PCS_TWIN_READ_WRITE_ENABLED"}
[WARN][2018-06-27 18:04:24.405][WebService.1511924f-fb25-40c8-8ddc-62c84c93fdd1][ConfigData:ProcessOptionalPlaceholders] Environment variables not found, {"varsNotFound":", PCS_SUBSCRIPTION_DOMAIN"}
[WARN][2018-06-27 18:04:24.405][WebService.1511924f-fb25-40c8-8ddc-62c84c93fdd1][ConfigData:ProcessOptionalPlaceholders] Environment variables not found, {"varsNotFound":", PCS_SUBSCRIPTION_ID"}
[WARN][2018-06-27 18:04:24.405][WebService.1511924f-fb25-40c8-8ddc-62c84c93fdd1][ConfigData:ProcessOptionalPlaceholders] Environment variables not found, {"varsNotFound":", PCS_RESOURCE_GROUP"}
[WARN][2018-06-27 18:04:24.405][WebService.1511924f-fb25-40c8-8ddc-62c84c93fdd1][ConfigData:ProcessOptionalPlaceholders] Environment variables not found, {"varsNotFound":", PCS_IOHUB_NAME"}
[WARN][2018-06-27 18:04:25.055][WebService.1511924f-fb25-40c8-8ddc-62c84c93fdd1][Startup:PrintBootstrapInfo] Service started, {"ProcessId":"WebService.1511924f-fb25-40c8-8ddc-62c84c93fdd1","LogLevel":"Warn"}
[WARN][2018-06-27 18:04:28.272][WebService.1511924f-fb25-40c8-8ddc-62c84c93fdd1][AuthMiddleware:.ctor] ### Service to service authentication is not available in public preview ###
[WARN][2018-06-27 18:04:28.278][WebService.1511924f-fb25-40c8-8ddc-62c84c93fdd1][AuthMiddleware:.ctor] ### Service to service authentication is not available in public preview ###
[WARN][2018-06-27 18:04:28.278][WebService.1511924f-fb25-40c8-8ddc-62c84c93fdd1][AuthMiddleware:.ctor] ### Service to service authentication is not available in public preview ###
Hosting environment: Production
Content root path: /app/webservice/
Now listening on: http://[::]:9003
Application started. Press Ctrl+C to shut down.
[WARN][2018-06-27 18:04:35.120][WebService.1511924f-fb25-40c8-8ddc-62c84c93fdd1][DeviceModels:GetAsync] Device model not found, {"id":"airglide-01"}
[ERROR][2018-06-27 18:04:35.189][WebService.1511924f-fb25-40c8-8ddc-62c84c93fdd1][SimulationRunner:Start] Unexpected error preparing the device model, {"Id":"airglide-01","e":{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Exceptions.ExternalDependencyException","ExceptionMessage":"Unable to load device model","StackTrace":"   at Microsoft.Azure.IoTSolutions.DeviceSimulation.SimulationAgent.SimulationRunner.GetDeviceModel(String id, DeviceModelOverride overrides) in C:\\Users\\John.Golding\\Cumulus\\GitHub\\device-simulation-dotnet\\SimulationAgent\\SimulationRunner.cs:line 301\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.SimulationAgent.SimulationRunner.Start(Simulation simulation) in C:\\Users\\John.Golding\\Cumulus\\GitHub\\device-simulation-dotnet\\SimulationAgent\\SimulationRunner.cs:line 191","Source":"Microsoft.Azure.IoTSolutions.DeviceSimulation.SimulationAgent","Data":{},"InnerException":{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Exceptions.ResourceNotFoundException","ExceptionMessage":"Exception of type 'Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Exceptions.ResourceNotFoundException' was thrown.","StackTrace":"   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceModels.<GetAsync>d__7.MoveNext() in C:\\Users\\John.Golding\\Cumulus\\GitHub\\device-simulation-dotnet\\Services\\DeviceModels.cs:line 98","Source":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services","Data":{},"InnerException":null}}}
[WARN][2018-06-27 18:04:35.210][WebService.1511924f-fb25-40c8-8ddc-62c84c93fdd1][DeviceModels:GetAsync] Device model not found, {"id":"airglide-02"}
[ERROR][2018-06-27 18:04:35.212][WebService.1511924f-fb25-40c8-8ddc-62c84c93fdd1][SimulationRunner:Start] Unexpected error preparing the device model, {"Id":"airglide-02","e":{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Exceptions.ExternalDependencyException","ExceptionMessage":"Unable to load device model","StackTrace":"   at Microsoft.Azure.IoTSolutions.DeviceSimulation.SimulationAgent.SimulationRunner.GetDeviceModel(String id, DeviceModelOverride overrides) in C:\\Users\\John.Golding\\Cumulus\\GitHub\\device-simulation-dotnet\\SimulationAgent\\SimulationRunner.cs:line 301\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.SimulationAgent.SimulationRunner.Start(Simulation simulation) in C:\\Users\\John.Golding\\Cumulus\\GitHub\\device-simulation-dotnet\\SimulationAgent\\SimulationRunner.cs:line 191","Source":"Microsoft.Azure.IoTSolutions.DeviceSimulation.SimulationAgent","Data":{},"InnerException":{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Exceptions.ResourceNotFoundException","ExceptionMessage":"Exception of type 'Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Exceptions.ResourceNotFoundException' was thrown.","StackTrace":"   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceModels.<GetAsync>d__7.MoveNext() in C:\\Users\\John.Golding\\Cumulus\\GitHub\\device-simulation-dotnet\\Services\\DeviceModels.cs:line 98","Source":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services","Data":{},"InnerException":null}}}

# Expected behavior 
New simulated devices and meta data are available, as per the lightbulb example in the demo.

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

# Code to reproduce the bug 
```
using Xunit;

public class MyTest
{
    [Fact]
    public void TestToReproduceIssue()
    {
        // Arrange
        ...

        // Act
        ...

        // Assert
        ...
    }
}
```

**Comment by JohnGolding** [comment]
I'm still having trouble with this issue - I don't know if anyone can help.
The issue still occurs whenever I tried to add any new unique device, regardless of whether it uses all of the properties and file structure from another device. Whilst the device appears on IOT hub when you deploy the microservice, it doesn't pull in any other parameters with it and the telemetry cannot start. My Microsoft support engineer has replicated the fault but is also struggling to figure this one out too. I am really eager to define a new device model and start testing the solution (which is excellent) with a real device at one of our sites. Can anyone out there please help me??

**Comment by troyhopwood** [comment]
The number one cause for this is usually an issue with the device model itself. I created an unofficial tool to test device models here: https://github.com/troyhopwood/IoT-Device-Simulation-Model-Tester. This is not an official Microsoft tool, but can be handy to validate device models. If the issue persists, it would be helpful to get the device model (JSON and JS files) to try to replicate.

**Comment by JohnGolding** [comment]
Thanks for this, Troy. I really appreciate you taking time to post the reply.
Unfortunately we've found that the tool only works with the building json/js files that come with the tool itself, and not with the actual json/js pairs within the pre-configured solution.
Apparently, it happens because of the updateState(state); line at the end of the main() function .
When this is replaced with the following it solves the problem:
 //updateState(state);
 return state;
Now all of the preconfigured solution json/js pairs work using your tool, and so do my own bespoke files.
However, this still does not solve my problem. Any ideas? I'm all out!
