### ISSUE TITLE
Refactor code to avoid blocking on waiting for the async method

### ISSUE THREAD

**Issue by maple10001** [Azure/device-simulation-dotnet#240]
# Type of issue 

- [ ] Bug
- [ ] New feature
- [x] Enhancement

# Description 
In `JavascriptInterpreter`, `LoadScriptAsync` is been waited in synchronize way,
which is not ideal under the best async practice.

More Info: [Best Practices in Asynchronous Programming](https://msdn.microsoft.com/en-us/magazine/jj991977.aspx)

**Comment by michal880** [comment]
I've submitted a PR for this, please check if it will do the job.
