### ISSUE TITLE
URI exception while running device simulation

### ISSUE THREAD

**Issue by AfreenShaha** [Azure/device-simulation-dotnet#301]
Not able to start the device simulation app. getting below error at line
var openIdConfig = await this.openIdCfgMan.GetConfigurationAsync(token)

As mentioned updated the connection string, still getting error.
iothub_connstring
-------------------------------------------------------------------------------------------------------------------
System.UriFormatException
  HResult=0x80131537
  Message=Invalid URI: The format of the URI could not be determined.
  Source=System.Private.Uri
  StackTrace:
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)

**Comment by tommo-ms** [comment]
@AfreenShaha - If you are still experiencing this could add more detailed repro steps?  Additionally, if you are running locally can you try turning off authentication by setting the PCS_AUTH_REQUIRED to false? P.S., if you are using Visual Studio you'll need to restart it after changing the environment variable.   

Thanks,
-Tom

**Comment by tommo-ms** [comment]
@AfreenShaha - Please reach out if you are still seeing this issue.  I'll go ahead and close for now until we have more feedback. 

Thanks,
-Tom
