### ISSUE TITLE
Will it simulate 10000 devices and send data paralley for 4 hrs ?

### ISSUE THREAD

**Issue by AfreenShaha** [Azure/device-simulation-dotnet#302]
Will this simulator simulates 20000 devices parallely? if yes then why in code count is always 4, for  sending telemetry data?
What if user wants to send 10000 devices data, how with 4 threads, parallelism will be achieved for 10000 devices?

for (int i = 0; i < count; i++)
                {
                    var task = this.factory.Resolve<IDeviceTelemetryTask>();
                    this.devicesTelemetryTasks.Add(task);

                    this.devicesTelemetryThreads[i] = new Thread(
                        () => task.RunAsync(this.deviceTelemetryActors, i + 1, count, this.runningToken.Token));
                    this.devicesTelemetryThreads[i].Start();
                }

**Comment by peterfelts** [comment]
This code creates four threads for sending telemetry data. Each thread sends data for 1/4 of all of the simulated devices. The value of four which you mentioned is the count of threads to use, which comes from the setting `telemetry_threads` in appsettings.ini.

It sounds like you're thinking that this code is only sending telemetry for four devices, but in fact it should be sending telemetry for all devices. That being said, I just fixed a bug where 25% of devices weren't having their telemetry sent (#306). 

> What if user wants to send 10000 devices data, how with 4 threads, parallelism will be achieved for 10000 devices?

Each thread runs RunAsync on an instance of IDeviceTelemetryTask. This method loops through all of the device actors and asks a subset of them to send telemetry. This subset is influenced by the value of telemetryThreadPosition which is passed to the RunAsync method (in the latest code). Hopefully the comment that I put in RunAsync in DeviceTelemetryTasks.cs does a fairly decent job of explaining how this works.

**Comment by AfreenShaha** [comment]
Thanks @peterfelts

**Comment by AfreenShaha** [comment]
Thanks @peterfelts .
Probably last query:
As I understand each thread will send data for multiple devices at once in batch at some user defined interval?
Please confirm.
