### ISSUE TITLE
404 accessing Storage adapter microservice link

### ISSUE THREAD

**Issue by asears** [Azure/device-simulation-dotnet#335]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
Storage adapter microservice used to store the simulation details - the link to this is broken in initial readme.md - repository no longer in github?

https://github.com/Azure/pcs-storage-adapter-dotnet/blob/master/README.md

...

# Steps to reproduce 

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
...

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

# Code to reproduce the bug 
```
using Xunit;

public class MyTest
{
    [Fact]
    public void TestToReproduceIssue()
    {
        // Arrange
        ...

        // Act
        ...

        // Assert
        ...
    }
}
```

**Comment by peterfelts** [comment]
Oops, we accidentally marked that repository as private. This has since been fixed. Thanks for letting us know about this and sorry for the trouble. Please let us know if you're still hitting this.
