### ISSUE TITLE
Wiki Page needs to be updated

### ISSUE THREAD

**Issue by siliang-jiao** [Azure/device-simulation-dotnet#347]
# Type of issue 

- [ ] Bug
- [ ] New feature
- [x] Enhancement

# Description 

Wiki page needs to be updated.
There are several mistakes in the api simulation wiki, such as 'deviceTypes' (which should be 'deviceModels'), lacking properties 'iothubs'.

# Steps to reproduce 

Update wiki page.

# Expected behavior 
Update wiki page.

**Comment by peterfelts** [comment]
I just made some updates and I think that @troyhopwood recently went through and made some updates as well. Thanks for letting us know about this and let us know if we missed anything else.
