### ISSUE TITLE
Custom device logic not executed

### ISSUE THREAD

**Issue by hoekj** [Azure/device-simulation-dotnet#349]
# Type of issue

- [ x] Bug
- [ ] New feature
- [ ] Enhancement

# Description
I've implemented a custom device model and a JavaScript file to handle custom state logic. Followed the wiki page and implemented the main function. The device message doesn't change and keeps sending its initial state (defined in the JSON file). Also tried to update the JavaScript file according to the state files in this GIT repo (f.e. chiller-01-state.js), but both scenario's doesn't work.

From the wiki:
`function main(context, previousState) {
//omitted state restore for readability
    state.payload = "test";
    return state;
}`

From chiller-01-state.js:
`function main(context, previousState, previousProperties) {
//omitted state restore for readability
    state.payload = "test";
    updateState(state);
}`

# Steps to reproduce 
Follow https://github.com/Azure/device-simulation-dotnet/wiki/Device-Models

# Expected behavior
Message on IotHub should show Payload="test" instead of Payload="initial State value defined in JSON"

# Current behavior 
Every message body in IotHub is the same

# Known workarounds
...

# Possible solution
...

# Context and Environment

**Comment by peterfelts** [comment]
I don't have the full JS file that you're using, but be sure that you're calling the [updateState](https://github.com/Azure/device-simulation-dotnet/blob/7a9dc7f427f42d2a9566ac587477bb2cad7768f3/Services/data/devicemodels/scripts/chiller-01-state.js#L92) method (you might also need the corresponding JInt (the JavaScript interpreter that we use from .Net) comments at the top of the file to hook up the callback in to .Net). This enables JInt to know to map that call back to .Net. It looks like our documentation here is wrong. Thanks for pointing this out. I'll take a look at it.

**Comment by peterfelts** [comment]
I updated the JavaScript examples on our wiki to reflect that methods should call the `updateState` callback.
