### ISSUE TITLE
Wiki uses incorrect data model to create new Simulations

### ISSUE THREAD

**Issue by murdockcrc** [Azure/device-simulation-dotnet#352]
This page:
https://github.com/Azure/device-simulation-dotnet/wiki/%5BAPI-Specifications%5D-Simulations#create-default-simulation

uses the following data model to POST a new simulation:

```
{
  "Enabled": true,
  "DeviceTypes": [
    {
      "Id": "truck-01",
      "Count": 3
    },
    {
      "Id": "truck-02",
      "Count": 1
    },
    {
      "Id": "elevator-01",
      "Count": 10
    }
  ]
}
```

However, property `DeviceTypes` is misnamed. The correct name is `DeviceModels`.

**Comment by peterfelts** [comment]
Fixed. Thanks for catching this.
