### ISSUE TITLE
IoT Solution: Device Simulation provisioning does not deploy resources

### ISSUE THREAD

**Issue by PurnaChandraPanda** [Azure/device-simulation-dotnet#355]
From the IoT Solutions site, I have been trying to provision a new `Device Simulation`. However, it shows provisioning for quite a long time – been more than 12 hours. I just see resource group created on Azure portal. However, there are no resources within it.

On a side note, I had the same simulation resource created earlier, which was working fine. I deleted the resource group/ spun up a new one (from accelerator site), where I have been stuck in the provisioning phase. Any thoughts what I should do to get the resources correctly provisioned?

resource group name: devicesimulation101

**Comment by peterfelts** [comment]
Which Azure region was this deployed to? I just performed a sanity check deployment to SE Asia and the deployment succeeded.

**Comment by PurnaChandraPanda** [comment]
It was west us2 region. It's being handled offline. I am am closing the issue.
