### ISSUE TITLE
Local Cosmos DB emulator does not work

### ISSUE THREAD

**Issue by ketulsheth** [Azure/device-simulation-dotnet#362]
# Type of issue
- [ x] Bug
- [ ] New feature
- [ ] Improvement

# Description 
I am trying to deploy the project on my local machine for development purpose. The goal is to only have IoT hub in the club and use local storage for device simulation. I am running Comos DB emulator app on my windows machine and was able to deploy the storage-adapter microservice which uses this local cosmos DB.

I am able to use the local storage adapter in this project, however, once the device simulation starts it is not able to use the cosmos DB because of the consistency level. 
It seems there is no way to change the consistency level in cosmos DB emulator.

My goal is to use local cosmos DB instead of cloud DB, is there any way to create such an environment ?

# Screenshot 

# Steps to reproduce 
1. Install Azure cosmos DB local emulator
2. Modify connection string in appsettings.ini for storage adapter to point to the local emulator connection string
3. Build and run storage adapter microservice
4. Use http://localhost:9022/v1/status as storage adapter URL in this project
5. Run this project and you should see the error message

# Context and Environment
* Operating System: Windows 10
* GitHub branch: ...
* .NET Runtime: ...

**Comment by troyhopwood** [comment]
As you have discovered, the emulator does not support different consistency levels. As such, the emulator is not supported with Device Simulation.
