### ISSUE TITLE
"ERROR:Unable to fetch simulation status;Unable to use Storage

### ISSUE THREAD

**Issue by coder-encoder** [Azure/device-simulation-dotnet#363]
Greetings Friends, i am using docker for simulation services and have following error in port 

http://127.0.0.1:9003/v1/status

{"Name":"DeviceSimulation","Status":"ERROR:Unable to fetch simulation status;Unable to use Storage","CurrentTime":"2019-10-09T12:34:47+00:00","StartTime":"2019-10-09T12:28:35+00:00","UpTime":372,"UID":"WebService.54d3f6bb-d1c8-4391-8ab5-1925ee5d3d9d","Properties":{"SimulationRunning":"unknown","PreprovisionedIoTHub":"true","ActiveDevicesCount":"0","TotalMessagesCount":"0","FailedMessagesCount":"0","MessagesPerSecond":"0.00","FailedDeviceConnectionsCount":"0","FailedDeviceTwinUpdatesCount":"0","SimulationErrorsCount":"0"},"Dependencies":{"Storage":"Status code: 0","PreprovisionedIoTHub":"OK"},"$metadata":{"$type":"Status;1","$uri":"/v1/status"}}

Thanks in advance for support

**Comment by peterfelts** [comment]
Make sure that you're also running the [storage adapter microservice](https://github.com/Azure/pcs-storage-adapter-dotnet/tree/c9d7d384b652657411cc4e40eb36edefd880e0be). The Simulation microservice requires the storage adapter.

Refer to [this](https://github.com/Azure/azure-iot-pcs-device-simulation) project for an overview of the requirements to run Simulation.

Please reactivate if this doesn't solve the error above.
