### ISSUE TITLE
consolidate sensor telemetry into single message

### ISSUE THREAD

**Issue by corywink** [Azure/device-simulation-dotnet#37]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
Devis was mentioning that there are separate messages for each sensor in a simulator. 
We need to consolidate these into a single message so that rules can be written against more than just a single value. I also believe that consolidation is how its done in general in reality due to bandwidth and costs constraints. 

# Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior

...

# Current behavior

...

# Known workarounds

...

# Possible solution

...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

# Code to reproduce the bug

```
using Xunit;

public class MyTest
{
    [Fact]
    public void TestToReproduceIssue()
    {
        // Arrange
        ...

        // Act
        ...

        // Assert
        ...
    }
}
```

**Comment by timlaverty** [comment]
done
