### ISSUE TITLE
Other resources links not resolving

### ISSUE THREAD

**Issue by hegate** [Azure/device-simulation-dotnet#39]
# Type of issue

- [X] Bug
- [ ] New feature
- [ ] Improvement

# Description
I'm clicking on the other resources link on the readme and getting 404s

Device Models specification
Simulation service API specs
Device Models API specs
Simulations API specs
...

**Comment by dluc** [comment]
I believe this is done, otherwise please reopen the issue

**Comment by nuno-andre** [comment]
Still broken. As in device simulation Java.

**Comment by ppathan** [comment]
Fixed.
