### ISSUE TITLE
Improve error when storage fails or is unavailable

### ISSUE THREAD

**Issue by timlaverty** [Azure/device-simulation-dotnet#41]
# Type of issue

- [x ] Bug
- [ ] New feature
- [x ] Improvement

# Description
When thestorage microservice can't be found (or fails) the error message is uninformative.  It should tell the developer what went wrong.

Error:
[SimulationAgent.b45b82d7-07a8-47d5-b322-548c3e19127a][2017-08-31 22:57:55Z][ERROR][Simulation:RunAsync] Unable to load simulation, {"e":{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Exceptions.ExternalDependencyException","ExceptionMessage":"An unexpected error happened while using an external dependency.","StackTrace":"   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.StorageAdapterClient.ThrowIfError(IHttpResponse response, String collectionId, String key) in C:\\source\\PCS2\\device-simulation-dotnet\\Services\\StorageAdapter\\StorageAdapterClient.cs:line 165\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.StorageAdapterClient.<GetAllAsync>d__7.MoveNext() in C:\\source\\PCS2\\device-simulation-dotnet\\Services\\StorageAdapter\\StorageAdapterClient.cs:line 85\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Simulations.<GetListAsync>d__7.MoveNext() in C:\\source\\PCS2\\device-simulation-dotnet\\Services\\Simulations.cs:line 46\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.SimulationAgent.Simulation.Simulation.<RunAsync>d__5.MoveNext() in C:\\source\\PCS2\\device-simulation-dotnet\\SimulationAgent\\Simulation\\Simulation.cs:line 46","Source":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services","Data":{},"InnerException":{"ExceptionFullName":"System.Net.Http.HttpRequestException","ExceptionMessage":"Storage request error: status code 0","StackTrace":null,"Source":null,"Data":{},"InnerException":null}}}

# Steps to reproduce

1. run simulation w/ no storage microservice endpoint up.

**Comment by dluc** [comment]
Done in the refactoring.  There might be room for improvements, but I'm closing this for now.  These are the 2 error messages generated when the service is unable to load the simulation.

>[ERROR][2017-11-30 08:26:23.607][WebService.393b4a94-56ec-4f15-a39b-32558b34c092][HttpClient:SendAsync] Request failed, {"timeSpent":139,"Method":"GET","Uri":"http://127.0.0.1:9022/v1/collections/simulations/values","errorMessage":"An error occurred while sending the request. - Couldn't connect to server","e":{"ExceptionFullName":"System.Net.Http.HttpRequestException","ExceptionMessage":"An error occurred while sending the request.","StackTrace":"   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\n   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Http.HttpClient.<SendAsync>d__9.MoveNext() in /builds/simulation/Services/Http/HttpClient.cs:line 92","Source":"System.Private.CoreLib","Data":{},"InnerException":{"ExceptionFullName":"System.Net.Http.CurlException","ExceptionMessage":"Couldn't connect to server","StackTrace":"   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)\n   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)","Source":"System.Net.Http","Data":{},"InnerException":null}}}

>[ERROR][2017-11-30 08:26:23.623][WebService.393b4a94-56ec-4f15-a39b-32558b34c092][Simulation:RunAsync] Failure reading and starting simulation from storage., {"e":{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Exceptions.ExternalDependencyException","ExceptionMessage":"An unexpected error happened while using an external dependency.","StackTrace":"   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.StorageAdapter.StorageAdapterClient.ThrowIfError(IHttpResponse response, String collectionId, String key) in /builds/simulation/Services/StorageAdapter/StorageAdapterClient.cs:line 175\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.StorageAdapter.StorageAdapterClient.<GetAllAsync>d__7.MoveNext() in /builds/simulation/Services/StorageAdapter/StorageAdapterClient.cs:line 82\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Simulations.<GetListAsync>d__8.MoveNext() in /builds/simulation/Services/Simulations.cs:line 50\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.SimulationAgent.Simulation.<RunAsync>d__7.MoveNext() in /builds/simulation/SimulationAgent/Simulation.cs:line 50","Source":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services","Data":{},"InnerException":{"ExceptionFullName":"System.Net.Http.HttpRequestException","ExceptionMessage":"Storage request error: status code 0","StackTrace":null,"Source":null,"Data":{},"InnerException":null}}}
```
