### ISSUE TITLE
Move UpdateState outside of Script Interpreter

### ISSUE THREAD

**Issue by timlaverty** [Azure/device-simulation-dotnet#45]
# Type of issue

- [x] Bug
- [ ] New feature
- [x] Improvement

# Description
Issue tracking this todo in the code:
        // TODO:Move this out of the scriptinterpreter class into DeviceClient to keep this class stateless

Make the class a singleton and review the "memory leak"

**Comment by dluc** [comment]
fixed in https://github.com/Azure/device-simulation-dotnet/pull/103
