### ISSUE TITLE
Make devices send multiple telemetry messages at once

### ISSUE THREAD

**Issue by timlaverty** [Azure/device-simulation-dotnet#52]
@hegate commented on [Tue Sep 05 2017](https://github.com/Azure/azure-iot-pcs-team/issues/87)

# Type of issue

- [ ] Bug
- [ ] New feature
- [X] Enhancement

# Description
Today, devices send different telemetry messages . We should consolidate messages so that we can send various telemetry messages at the same time (think rules, etc.)
...

---

@timlaverty commented on [Tue Sep 05 2017](https://github.com/Azure/azure-iot-pcs-team/issues/87#issuecomment-327274596)

When we do this we need to test the TelemetryAgent with multi-telemetry type rules

**Comment by dluc** [comment]
I believe this work was done in July/August. Device models allow to define multiple telemetry messages, with different frequency if needed. @timlaverty Could you confirm?

**Comment by timlaverty** [comment]
This was done with https://github.com/Azure/device-simulation-dotnet/pull/65
