### ISSUE TITLE
Docs: Show how to allow a different user than the person that provisioned an application to use it.

### ISSUE THREAD

**Issue by timlaverty** [Azure/device-simulation-dotnet#53]
# Type of issue

- [ ] Bug
- [x ] New feature
- [x ] Improvement

# Description
Right now only the person that provisioned an app will be able to view it.  We need explain how users can be added to the app.

We should update the permissions doc for azureiotsuite.com that already exists for this.

**Comment by troyhopwood** [comment]
Anyone with access to that Active Directory can access the deployed solution.
