### ISSUE TITLE
message delivery failed increasing over time

### ISSUE THREAD

**Issue by timlaverty** [Azure/device-simulation-dotnet#60]
@maple10001 commented on [Mon Sep 25 2017](https://github.com/Azure/telemetry-agent-dotnet/issues/23)

# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description

 'message delivery failed' message in simulation increasing over time

# Steps to reproduce

1. start a new deployment
2. open logs for simulation agent

# Expected behavior

simulation agent deliver all messages

# Current behavior

successful delivery rate droping over time

# Known workarounds

- restart services every 3 mins

![image](https://user-images.githubusercontent.com/8744187/30822670-6272952c-a1de-11e7-95d6-39c5f009e122.png)

---

@xzsheng commented on [Mon Sep 25 2017](https://github.com/Azure/telemetry-agent-dotnet/issues/23#issuecomment-332066425)

It is an exception raised from the `simulation service` rather than `telemetry agent`. It means the simulation service failed to send message to IoTHub.

@timlaverty Shall we move this issue to the simulation service repo?

**Comment by dluc** [comment]
Closing as fixed by https://github.com/Azure/device-simulation-dotnet/pull/137
