### ISSUE TITLE
Make Timer use in hub related operations non-reentrant

### ISSUE THREAD

**Issue by timlaverty** [Azure/device-simulation-dotnet#73]
# Type of issue

- [x ] Bug
- [ ] New feature
- [ ] Enhancement

# Description
Change the Timer use so operations that involve touching the hub aren’t reentrant; i.e. add a Pause and Unpause method to the Timer and implement it in each of SendTelemetry and UpdateDesiredProperties....

**Comment by dluc** [comment]
done
