### ISSUE TITLE
Define connection, messaging etc. default limits for Remote Monitoring Basic and Standard Deployments

### ISSUE THREAD

**Issue by dluc** [Azure/device-simulation-dotnet#93]
# Type of issue 

- [ ] Bug
- [x] New feature
- [ ] Enhancement

# Description 

See `appsettings.ini`, set the values we want to use for Remote Monitoring deployments

**Comment by timlaverty** [comment]
Suggest limiting to ~1/2 the available hub SKU/unit limit to allow for clients outside the simulator leeway - i.e. we should not always run the simulator @ capacity.

**Comment by timlaverty** [comment]
This makes sense - these look good.

**Comment by timlaverty** [comment]
done
